

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid
    username: root
    password: NOVASENHA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    generate-ddl: true